Update codeql.yml

diff --git a/.github/workflows/codeql.yml b/.github/workflows/codeql.yml
--- a/.github/workflows/codeql.yml
+++ b/.github/workflows/codeql.yml
@@ -8,6 +8,7 @@
 # We have attempted to detect the languages in your repository. Please check
 # the `language` matrix defined below to confirm you have the correct set of
 # supported CodeQL languages.
+#
 name: "CodeQL Advanced"
 
 on:
@@ -16,20 +17,24 @@ on:
   pull_request:
     branches: [ "develop" ]
   schedule:
-    - cron: '38 14 * * 3'
+    - cron: '26 18 * * 3'
 
 jobs:
   analyze:
     name: Analyze (${{ matrix.language }})
-    # Runner matrices configure machines that will run the jobs.
-    # We recommend choosing the latest available version for each OS.
-    # Info: https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idruns-on
+    # Runner size impacts CodeQL analysis time. To learn more, please see:
+    #   - https://gh.io/recommended-hardware-resources-for-running-codeql
+    #   - https://gh.io/supported-runners-and-hardware-resources
+    #   - https://gh.io/using-larger-runners (GitHub.com only)
+    # Consider using larger runners or machines with greater resources for possible analysis time improvements.
     runs-on: ${{ (matrix.language == 'swift' && 'macos-latest') || 'ubuntu-latest' }}
     permissions:
       # required for all workflows
       security-events: write
+
       # required to fetch internal or private CodeQL packs
       packages: read
+
       # only required for workflows in private repositories
       actions: read
       contents: read
@@ -38,17 +43,29 @@ jobs:
       fail-fast: false
       matrix:
         include:
-        # If you wish to specify build modes, you can do so here. Build modes can be 'autobuild', 'manual', or 'none'
-        # If you are using workflow_call, be aware that the build mode is dictated by the caller workflow
-        # Learn more at https://docs.github.com/en/code-security/code-scanning/automatically-scanning-your-code-for-vulnerabilities-and-errors/configuring-code-scanning#using-a-build-mode
+        - language: actions
+          build-mode: none
         - language: java-kotlin
-          build-mode: manual # Set to 'manual' because we provide build steps below
+          build-mode: autobuild
         - language: javascript-typescript
-          build-mode: none    # 'none' indicates no build is required for CodeQL to analyze these languages
-
+          build-mode: none
+        # CodeQL supports the following values keywords for 'language': 'actions', 'c-cpp', 'csharp', 'go', 'java-kotlin', 'javascript-typescript', 'python', 'ruby', 'swift'
+        # Use `c-cpp` to analyze code written in C, C++ or both
+        # Use 'java-kotlin' to analyze code written in Java, Kotlin or both
+        # Use 'javascript-typescript' to analyze code written in JavaScript, TypeScript or both
+        # To learn more about changing the languages that are analyzed or customizing the build mode for your analysis,
+        # see https://docs.github.com/en/code-security/code-scanning/creating-an-advanced-setup-for-code-scanning/customizing-your-advanced-setup-for-code-scanning.
+        # If you are analyzing a compiled language, you can modify the 'build-mode' for that language to customize how
+        # your codebase is analyzed, see https://docs.github.com/en/code-security/code-scanning/creating-an-advanced-setup-for-code-scanning/codeql-code-scanning-for-compiled-languages
     steps:
     - name: Checkout repository
       uses: actions/checkout@v4
+
+    # Add any setup steps before running the `github/codeql-action/init` action.
+    # This includes steps like installing compilers or runtimes (`actions/setup-node`
+    # or others). This is typically only required for manual builds.
+    # - name: Setup runtime (example)
+    #   uses: actions/setup-example@v1
 
     # Initializes the CodeQL tools for scanning.
     - name: Initialize CodeQL
@@ -63,27 +80,22 @@ jobs:
         # For more details on CodeQL's query packs, refer to: https://docs.github.com/en/code-security/code-scanning/automatically-scanning-your-code-for-vulnerabilities-and-errors/configuring-code-scanning#using-queries-in-ql-packs
         # queries: security-extended,security-and-quality
 
-    # *** DEBUGGING STEP ***
-    # List files to see if gradlew is present after checkout
-    - name: List files in workspace
-      run: ls -la
-      if: matrix.language == 'java-kotlin' # Only run for the Java/Kotlin job
-
-    # ℹ️ This is the customized build step for Java/Kotlin using Gradle.
-    #     -> Ensure 'gradlew' exists in your repository root for the commit being built. <-
-    #     -> Adjust './gradlew clean build' if your command is different. <-
-    #     -> If build needs to run in a sub-directory, add 'cd your-sub-dir' first. <-
-    - if: matrix.language == 'java-kotlin' && matrix.build-mode == 'manual'
-      name: Build Java-Kotlin project (Gradle)
+    # If the analyze step fails for one of the languages you are analyzing with
+    # "We were unable to automatically build your code", modify the matrix above
+    # to set the build mode to "manual" for that language. Then modify this step
+    # to build your code.
+    # ℹ️ Command-line programs to run using the OS shell.
+    # 📚 See https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idstepsrun
+    - if: matrix.build-mode == 'manual'
+      shell: bash
       run: |
-        echo "Attempting to build with Gradle..."
-        # Grant execute permission just in case (may not be necessary if git permissions are correct)
-        # This command will fail if 'gradlew' is not found by the 'ls' step above.
-        chmod +x gradlew
-        # Run the build command
-        ./gradlew clean build
+        echo 'If you are using a "manual" build mode for one or more of the' \
+          'languages you are analyzing, replace this with the commands to build' \
+          'your code, for example:'
+        echo '  make bootstrap'
+        echo '  make release'
+        exit 1
 
-    # Perform CodeQL Analysis
     - name: Perform CodeQL Analysis
       uses: github/codeql-action/analyze@v3
       with:
